## WiSHFUL Controllers config file

discovery_module:
    type : python
    path : ../../wishful_driver_discovery/bin/discovery_pyre_controller
    args : ['']

synchronization_module:
    type : python
    path : ../../wishful_module_ptp/bin/ptp_server.py
    args : ['-i eth0']